# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0018_add_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_ids',
            field=models.BooleanField(default=False, help_text=b'Show click-to-copy patch IDs in the list view'),
        ),
    ]
