# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0019_userprofile_show_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='show_column',
            field=models.BooleanField(default=True, help_text=b"Show a column displaying this tag's count in the patch list view"),
        ),
    ]
