# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0027_remove_series_ordering'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['submission', 'date'], name='submission_date_idx'),
        ),
    ]
