# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0029_add_list_covering_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['date', 'project', 'submitter', 'name'], name='submission_covering_idx'),
        ),
    ]
