# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0033_remove_patch_series_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='list_archive_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
