# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0034_project_list_archive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='list_archive_url_format',
            field=models.CharField(blank=True, help_text=b"URL format for the list archive's Message-ID redirector. {} will be replaced by the Message-ID.", max_length=2000),
        ),
    ]
