# Generated by Django 3.1.12 on 2021-08-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0044_add_project_linkname_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='covercomment',
            name='addressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patchcomment',
            name='addressed',
            field=models.BooleanField(default=False),
        ),
    ]
