# Generated by Django 5.0.6 on 2024-06-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0046_patch_comment_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='dependencies',
            field=models.ManyToManyField(
                blank=True,
                help_text='Optional dependencies on this patch.',
                related_name='dependents',
                related_query_name='dependent',
                to='patchwork.series',
            ),
        ),
    ]
