# Generated by Django 5.0.2 on 2024-03-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0046_patch_comment_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='related_series',
            field=models.ManyToManyField(to='patchwork.series'),
        ),
    ]
