# Generated by Django 4.2.7 on 2024-01-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0046_patch_comment_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mid_scheme',
            field=models.CharField(
                blank=True,
                help_text='URL scheme to use when opening message IDs',
                max_length=255,
            ),
        ),
    ]
