# Generated by Django 5.1.2 on 2024-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0047_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='previous_series',
            field=models.ManyToManyField(
                related_name='subsequent_series', to='patchwork.series'
            ),
        ),
        migrations.AddField(
            model_name='series',
            name='required_series',
            field=models.ManyToManyField(
                related_name='required_by_series', to='patchwork.series'
            ),
        ),
    ]
