# Generated by Django 5.0.4 on 2024-04-16 04:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0047_add_database_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='has_planned_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='review_intention_expiration_time',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
        migrations.CreateModel(
            name='PatchReviewIntention',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'last_time_marked_for_review',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'patch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='patchwork.patch',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('patch', 'user')},
            },
        ),
        migrations.AddField(
            model_name='patch',
            name='planning_to_review',
            field=models.ManyToManyField(
                related_name='planning_to_review',
                through='patchwork.PatchReviewIntention',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
