# Generated by Django 5.1.7 on 2025-03-22 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0048_series_dependencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchAttentionSet',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                (
                    'removed_reason',
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    'patch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='patchwork.patch',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('patch', 'user')},
            },
        ),
        migrations.AddField(
            model_name='patch',
            name='attention_set',
            field=models.ManyToManyField(
                related_name='attention_set',
                through='patchwork.PatchAttentionSet',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
