# Generated by Django 5.1.4 on 2025-03-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0048_series_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='supersedes',
            field=models.ManyToManyField(
                blank=True,
                help_text='Previous versions of this patch.',
                related_name='superseded',
                to='patchwork.series',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='show_series_versions',
            field=models.BooleanField(
                default=False,
                help_text='Enable parsing series previous versions on patches '
                'and cover letters.',
            ),
        ),
    ]
