# Generated by Django 5.1.2 on 2024-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0048_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
